### ISSUE TITLE
多开软件闪退之后Xposed Manager中的插件变为不可见

### ISSUE THREAD

**Issue by y702332688** [ganyao114/SandVXposed#20]
测试机型：vivox20A
软件版本：SandVXP 0.0.9.1 Alpha
出现问题：
1.启用微X插件后微信闪退，再次进入Xposed Manager，插件变为不可见；
2.SandVXposed在app管理页面时每次进入SandVXposed都是重新启动，其他页面直接进入；
3.创建快捷方式时有闪退情况；
4.SandVXposed启动状态下通过快捷方式直接进入管理页面而不启动APP，SandVXposed关闭状态可启动(建议：不进入SandVXposed页面，而是全屏底色，中间软件图标，底部吃豆)
5.点击 设置->应用设置->返回，直接闪退
6.安装页面，“手动选择路径安装”铺盖图标，建议位于右上角或底部安装按钮并排
7.虚拟位置无效，设置后定位依旧是实际位置

**Comment by ghost** [comment]
1. 微X模块有问题，暂时用V++替代
2. 返回键以后就会把主页结束掉的，请用主页键保持后台
3. 回调函数的问题，算是BUG，会解决
4. 可以实现
5. 会修复（其实是未实现的功能）
6. 可以，xml补一句的问题
7. Android O以后虚拟位置暂时不生效

**Comment by y702332688** [comment]
> 1. 微X模块有问题，暂时用V++替代
> 2. 返回键以后就会把主页结束掉的，请用主页键保持后台
> 3. 回调函数的问题，算是BUG，会解决
> 4. 可以实现
> 5. 会修复（其实是未实现的功能）
> 6. 可以，xml补一句的问题
> 7. Android O以后虚拟位置暂时不生效

1.我不是说的WX有问题，我是说闪退后Xposed Manager列表中插件都不可见了，启动svx才可见
2.我没有按返回键，无论怎么返回的手机桌面，在桌面打开svx都是重新启动

**Comment by y702332688** [comment]
> 1. 微X模块有问题，暂时用V++替代
> 2. 返回键以后就会把主页结束掉的，请用主页键保持后台
> 3. 回调函数的问题，算是BUG，会解决
> 4. 可以实现
> 5. 会修复（其实是未实现的功能）
> 6. 可以，xml补一句的问题
> 7. Android O以后虚拟位置暂时不生效

1的问题，Xposed Manager列表中插件都不可见了不说，克隆APP页面 应用列表也获取不到了

**Comment by y702332688** [comment]
> 1. 微X模块有问题，暂时用V++替代
> 2. 返回键以后就会把主页结束掉的，请用主页键保持后台
> 3. 回调函数的问题，算是BUG，会解决
> 4. 可以实现
> 5. 会修复（其实是未实现的功能）
> 6. 可以，xml补一句的问题
> 7. Android O以后虚拟位置暂时不生效

已加你QQ，不明白什么意思话 我给你录屏  你看下
