### ISSUE TITLE
Xposed Installer 不能正常工作

### ISSUE THREAD

**Issue by iamdrq** [ganyao114/SandVXposed#34]
Xposed Installer 不能正常工作
![Screenshot_2019-05-17-17-48-15-117_io virtualapp](https://user-images.githubusercontent.com/11384110/57919789-228f7800-78cc-11e9-99b8-1d5e1b0b0d38.png)
我需要Xposed Installer的查看日志功能做调试，该如何解决呢？

**Comment by ganyao114** [comment]
本身是不支持 xp installer is的，因为不是 root 环境

**Comment by iamdrq** [comment]
好的。那可以支持xp installer的日志功能吗？
