### ISSUE TITLE
能把hookzz,等没用的清理掉吗

### ISSUE THREAD

**Issue by menglinxi** [ganyao114/SandVXposed#4]
能把hookzz,等没用的清理掉吗?编译出来的包体有点大

**Comment by ganyao114** [comment]
> 能把hookzz,等没用的清理掉吗?编译出来的包体有点大

hookzz 并没有编译进去，4M 的体积不算大吧

**Comment by menglinxi** [comment]
建议用vxp最新版本,融合 sandhook,这样兼容性更好点

**Comment by ganyao114** [comment]
> 建议用vxp最新版本,融合 sandhook,这样兼容性更好点

先试用吧，有问题提给我

**Comment by menglinxi** [comment]
好的,在试用.感谢这个项目,持续关注中.
