### ISSUE TITLE
添加app时”内部存储设备“空白

### ISSUE THREAD

**Issue by weimingjue** [ganyao114/SandVXposed#40]
红米not7pro，android9.0
点击添加app，然后内部存储设备页面是空的，有SD卡权限，没任何报错信息

**Comment by ghost** [comment]
请点击右下+号添加，或者将安装包复制到内部存储根目录~~

**Comment by weimingjue** [comment]
复制到根目录...好吧，不说谁知道......

**Comment by weimingjue** [comment]
还有 @lianglixin 天猫闪退的问题有解决吗
