### ISSUE TITLE
微信经常被挤掉 提示在其他手机登录

### ISSUE THREAD

**Issue by zy990081568** [ganyao114/SandVXposed#49]
![image](https://user-images.githubusercontent.com/10340599/59997933-ba813e00-9690-11e9-9813-483c98238362.png)

是在同一台手机上, 账号经常会被挤掉, 要重新登录

**Comment by goldencolor** [comment]
你 解决了吗？

**Comment by zy990081568** [comment]
> 你 解决了吗？

把多开限制成一个好像就没有这个问题了, 就是userId永远是0
