### ISSUE TITLE
classpath 'com.android.tools.build:gradle-experimental:3.3.0'

### ISSUE THREAD

**Issue by menglinxi** [ganyao114/SandVXposed#5]
这个依赖是必须么？到处都下载不到
Could not find com.android.tools.build:gradle-experimental:3.3.0.

**Comment by ganyao114** [comment]
> 这个依赖是必须么？到处都下载不到
> Could not find com.android.tools.build:gradle-experimental:3.3.0.

挂 VPN 试试

**Comment by menglinxi** [comment]
![image](https://user-images.githubusercontent.com/3926945/55942340-c86d1880-5c76-11e9-9002-a28e31241333.png)

**Comment by menglinxi** [comment]
ERROR: Failed to resolve: com.android.support.constraint:constraint-layout:1.1.3
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:appcompat-v7:28.0.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:percent:28.0.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:design:28.0.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:cardview-v7:28.0.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app, lib


WARNING: The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: lib

**Comment by ganyao114** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.android.tools.build:gradle-experimental:0.11.0'
        classpath 'com.trend.lazyinject:aopweave:3.4.0-beta'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



把 google maven 提到前面试试

**Comment by menglinxi** [comment]
classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.android.tools.build:gradle-experimental:0.11.0'

这样才是对的，然后现在项目里的3.3.0有问题，麻烦楼主修改一下，避免其他兄弟走弯路。

gradle，不能更新到4.10.1

**Comment by ganyao114** [comment]
> ```
>     classpath 'com.android.tools.build:gradle:3.0.1'
>     classpath 'com.android.tools.build:gradle-experimental:0.11.0'
> ```
> 
> 这样才是对的，然后现在项目里的3.3.0有问题，麻烦楼主修改一下，避免其他兄弟走弯路。
> 
> 
> gradle，不能更新到4.10.1

3.3.0 是你自己改的吧。。。 我一直是 0.11.0

**Comment by menglinxi** [comment]
嗯，已经搞定了，感谢楼主
