### ISSUE TITLE
Android10适配

### ISSUE THREAD

**Issue by zy990081568** [ganyao114/SandVXposed#64]
Android10上面很不稳定, 经常打不开微信, 请问什么时候能完全适配呀?

**Comment by tianyah** [comment]
真实桌面上不安装微信，然后选择在存储空间添加微信，在华为手机上会 java.lang.RuntimeException: Unable to create application com.tencent.mm.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
