### ISSUE TITLE
Not Working in Samsung Galaxy

### ISSUE THREAD

**Issue by Goxome** [ganyao114/SandVXposed#71]
Deleted

**Comment by ghost** [comment]
你好，请提供报错日志，并提供系统版本、UI版本以及具体的截图

**Comment by TipzTeam** [comment]
> 你好，请提供报错日志，并提供系统版本、UI版本以及具体的截图

He is not a Chinese, but I will help you translate to him (cuz I am a Chinese)

**Comment by TipzTeam** [comment]
> Please help
> After clone
> Apps are not launching!.....

@lianglixin Hello, please provide error logs, and also provide software version, UI version and more detailed screenshots.
